name: Deploy LMS

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Prepare server directory
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DIR: ${{ secrets.SERVER_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 1337 $USERNAME@$SERVER_IP "
            sudo mkdir -p $SERVER_DIR || exit 1
            sudo chown $USERNAME:$USERNAME $SERVER_DIR || exit 1
            sudo chmod 755 $SERVER_DIR || exit 1
          "

      - name: Build backend
        run: |
          go build -o lms_back
          ls -lh lms_back

      - name: Upload to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DIR: ${{ secrets.SERVER_DIR }}
        run: |
          rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 1337" ./ $USERNAME@$SERVER_IP:$SERVER_DIR

      - name: Restart backend service
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
          SERVER_DIR: ${{ secrets.SERVER_DIR }}
        run: |
          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 1337 $USERNAME@$SERVER_IP "
            sudo systemctl restart lms_back || 
            (sudo pkill lms_back; nohup $SERVER_DIR/lms_back > /dev/null 2>&1 &)
          "
